baseURL = "https://romantic-spence-51b514.netlify.com/"
languageCode = "en-us"
title = "Vic Space"
theme = "hermit"


[author]
  name = "Vittorio Camisa"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = ""
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "linkedin"
    url = "https://it.linkedin.com/in/vittorio-camisa/en"

  [[params.social]]
    name = "github"
    url = "https://github.com/Provok"

[menu]

  [[menu.main]]
    name = "About me"
    url = "about"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 10
